name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: sudo -E env "PATH=$PATH" make install
    - name: Tests
      run: |
        sudo rm $(which yq)  # need to clean the old yq available in the workers
        sudo -E env "PATH=$PATH" make install_luet  # some extensions use luet (i.e. autobump-github) for testing
        make test
